# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: clegirar <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/22 09:46:01 by clegirar          #+#    #+#              #
#    Updated: 2017/07/22 10:15:56 by clegirar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	=	comp

all		:	$(NAME)

$(NAME)	:
			make -C colle00
			make -C colle02

clean	:
			make clean -C colle00
			make clean -C colle02

fclean	:
			make fclean -C colle00
			make fclean -C colle02

re		:
			make re -C colle00
			make re -C colle02
