# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: clegirar <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/22 09:52:30 by clegirar          #+#    #+#              #
#    Updated: 2017/07/22 10:15:45 by clegirar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	=	comp

all		:	$(NAME)

$(NAME)	:
			make -C rush00
			make -C rush01
			make -C rush02
			make -C rush03
			make -C rush04

clean	:
			make clean -C rush00
			make clean -C rush01
			make clean -C rush02
			make clean -C rush03
			make clean -C rush04

fclean	:
			make fclean -C rush00
			make fclean -C rush01
			make fclean -C rush02
			make fclean -C rush03
			make fclean -C rush04

re		:
			make re -C rush00
			make re -C rush01
			make re -C rush02
			make re -C rush03
			make re -C rush04
